// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtS8vNGy2hpFMeA4aAIYS75S6NBsmZE6g',
    appId: '1:777550117901:web:a67f06bb635e464f252944',
    messagingSenderId: '777550117901',
    projectId: 'smart-bite-444717',
    authDomain: 'smart-bite-444717.firebaseapp.com',
    storageBucket: 'smart-bite-444717.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_0DDfvBlATVYCh5l_mo8vEombF542FVk',
    appId: '1:777550117901:android:8d21e1596a6345cf252944',
    messagingSenderId: '777550117901',
    projectId: 'smart-bite-444717',
    storageBucket: 'smart-bite-444717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUKAmJHkpAjCAZVTC9Jtjbo2vU2N61DMI',
    appId: '1:777550117901:ios:94bc2ffc31b11b6b252944',
    messagingSenderId: '777550117901',
    projectId: 'smart-bite-444717',
    storageBucket: 'smart-bite-444717.firebasestorage.app',
    iosBundleId: 'com.example.smartBite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUKAmJHkpAjCAZVTC9Jtjbo2vU2N61DMI',
    appId: '1:777550117901:ios:94bc2ffc31b11b6b252944',
    messagingSenderId: '777550117901',
    projectId: 'smart-bite-444717',
    storageBucket: 'smart-bite-444717.firebasestorage.app',
    iosBundleId: 'com.example.smartBite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtS8vNGy2hpFMeA4aAIYS75S6NBsmZE6g',
    appId: '1:777550117901:web:1f552325eb34aa99252944',
    messagingSenderId: '777550117901',
    projectId: 'smart-bite-444717',
    authDomain: 'smart-bite-444717.firebaseapp.com',
    storageBucket: 'smart-bite-444717.firebasestorage.app',
  );
}
